### ISSUE TITLE
ERR Protocol error: too big inline request

### ISSUE THREAD

**Issue by denro** [gosexy/redis#3]
Hi, don't know if this is a problem related to my crappy code, these go-bindings, hiredis or redis:

When calling a lot of redis commands, maybe a few thousand a second, through a single connection I get this strange error: `Protocol error: too big inline request`.

While trying to debug this i find that the error is being raised in redis when the queue(?) goes too big or at least exceeds a constant named  `REDIS_INLINE_MAX_SIZE`: https://github.com/antirez/redis/blob/unstable/src/networking.c#L892-L900

is this something i should be thinking about? not throwing too much at redis? would multiple connections do better? THANKS!

**Comment by cansin** [comment]
@sosogh thanks, I was having a similar problem and running `unix2dos` on the input file fixed it for me.
